### ISSUE TITLE
Test new Feature

### ISSUE THREAD

**Issue by Ryad3** [INFOM126-Automated-Software-Engineering/2048_Groupe_10#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the feature request template to include all required sections and improve the clarity of instructions.

You can review changes in this commit: https://github.com/mnmnk43434/INFOM126-Automated-Software-Engineering-2048_Groupe_10-33/commit/287b3765482a04aedfb4cf1eed5d1dcd01c3421b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
